sonar.projectKey=proyecto_eym
sonar.projectName=Proyecto EYM
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.sourceEncoding=UTF-8


sonar.login=squ_586a71d8229a3e62be60973ca9942d325ddf2495

sonar.java.binaries=target/classes
