sonar.projectKey=proyecto_eym
sonar.projectName=Proyecto EYM
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.sourceEncoding=UTF-8


sonar.login=squ_0370923fec133a32b75d58d72baaee3f9952807a

sonar.java.binaries=target/classes
